mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
ipv6: false
#dns: #DNS 设置一般无需打开，如果你坚持想用，请确保你知道在做什么
  #enable: true
  #listen: 0.0.0.0:53
  #ipv6: false
  #default-nameserver:
    #- 223.5.5.5
    #- 119.29.29.29
  #enhanced-mode: redir-host
  #nameserver:
    #- https://doh.pub/dns-query
    #- https://dns.alidns.com/dns-query
  #fallback:
    #- https://1.1.1.1/dns-query
    #- https://dns.google/dns-query
  #fallback-filter:
    #geoip: true
    #geoip-code: CN
    #ipcidr:
      #- 240.0.0.0/4

proxy-providers:
  myproxy:
    type: http
    url: https://gist.githubusercontent.com/tiandongxv/69b4af3efb2fa5920e174b9201685352/raw/clash
    interval: 172800
    path: ./myproxy.yaml
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: http://www.gstatic.com/generate_204

proxy-groups:
  - name: "PROXY"
    type: select
    use:
      - myproxy
  - name: "Others"
    type: select
    proxies:
      - PROXY
      - DIRECT

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

rules:
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,proxy,PROXY
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT,no-resolve
  - RULE-SET,cncidr,DIRECT
  - GEOIP,LAN,DIRECT,no-resolve
  - GEOIP,CN,DIRECT
  - MATCH,Others